-- Generated by tools/convert-buttons.js - don't edit. Each button state's art: its size and the size of
-- the texture it sits in (top-left). Textures: Media/Button/<state>.blp. See ns.UI.SkinButton.

local _, ns = ...

ns.ButtonArt = {
    normal = { width = 234, height = 98, textureWidth = 256, textureHeight = 128 },
    hover = { width = 242, height = 107, textureWidth = 256, textureHeight = 128 },
    pushed = { width = 225, height = 94, textureWidth = 256, textureHeight = 128 },
    selected = { width = 242, height = 107, textureWidth = 256, textureHeight = 128 },
}
