-- Generated by tools/header-layout.js - don't edit; change the layout there and rerun it.
-- The wooden header along the top of the main window (UI.lua): planks { x, y (centre, from the window's top-left,
-- y down), w, h, tilt (degrees clockwise), texture, shade (1 = as painted) } in drawing order, and the square buttons { x, y (top-left), w,
-- h, icon, iconSize }.

local _, ns = ...

ns.HeaderLayout = {
    planks = {
        { x = 250, y = 10, w = 142, h = 26, tilt = -1.9, texture = "Plank", shade = 0.85 },
        { x = 460, y = 17, w = 252, h = 26, tilt = 0.7, texture = "Plank", shade = 0.85 },
        { x = 710, y = 14, w = 232, h = 26, tilt = 0.4, texture = "Plank", shade = 0.85 },
        { x = 292, y = 35, w = 226, h = 36, tilt = 2.5, texture = "Plank", shade = 1 },
        { x = 475, y = 31, w = 250, h = 36, tilt = 0, texture = "Plank", shade = 1 },
        { x = 712, y = 34, w = 230, h = 33, tilt = -0.3, texture = "Plank", shade = 1 },
        { x = 408, y = 56, w = 64, h = 36, tilt = 50, texture = "Piece", shade = 0.95 },
        { x = 600, y = 19, w = 54, h = 42, tilt = -12, texture = "Piece", shade = 1 },
    },
    buttons = {
        settings = { x = 818, y = 4, w = 53, h = 50, icon = "Settings", iconSize = 26, runes = true },
        close = { x = 870, y = -4, w = 76, h = 60, icon = "Close", iconSize = 48 },
    },
    plankEnd = 0.645,
    runeHeight = 0.6,
}
