-- Generated by tools/convert-logo.js - don't edit. Visible parts of Media/Logo.blp: per row (top to bottom),
-- runs of mostly opaque cells { first, last } in a 21 x 21 grid. See UI.lua (dragging by the logo).

local _, ns = ...

ns.LogoMask = { cells = 21, rows = {
    {  },
    {  },
    {  },
    {  },
    { { 11, 13 } },
    { { 7, 13 } },
    { { 6, 16 } },
    { { 3, 20 } },
    { { 2, 20 } },
    { { 2, 20 } },
    { { 2, 20 } },
    { { 1, 21 } },
    { { 2, 21 } },
    { { 2, 20 } },
    { { 2, 20 } },
    { { 2, 20 } },
    { { 3, 20 } },
    { { 3, 20 } },
    { { 4, 4 }, { 18, 19 } },
    {  },
    {  },
} }
