-- Pseudo-minting: a picture is a stack of layers (background, skin, outfit, expression, eyes, accessory,
-- headwear). Minting rolls one option per layer, weighted by rarity, and saves only the result in
-- KillTrackerDB.mints = { { number, traits = { [layer key] = option id }, time, claim } }. Pictures are
-- drawn by stacking the chosen layer images; a backend can rebuild the same picture from the traits.
--
-- Art: the options and their textures come from MintArt.lua, generated by tools/convert-art.js from the
-- PNGs in tools/art-source. Options with perSkin have one texture per skin (eyes and mouths drawn in
-- the skin's colour), picked by the picture's skin trait.

local _, ns = ...

-- The price of a mint is a guild setting (Config.lua); each picture remembers what it cost.
function ns.MintCost() return ns.Config("mintCost") end

local RARITY_WEIGHTS = { common = 60, uncommon = 25, rare = 10, epic = 4, legendary = 1 }
local RARITY_SCORE = { common = 0, uncommon = 1, rare = 2, epic = 3, legendary = 4 }
local RARITY_ORDER = { "common", "uncommon", "rare", "epic", "legendary" }
-- A picture's overall rarity: the share of all rolls that score at least as high (see ns.MintRarity).
local PICTURE_TIERS = { { "legendary", 0.015 }, { "epic", 0.05 }, { "rare", 0.17 }, { "uncommon", 0.55 } }

-- Layers from back to front; options { id (never change once released), name, rarity, texture, rect,
-- perSkin } from MintArt.lua. rect = { x, y, width, height } as fractions of the picture places a
-- cropped image; options without one cover the whole picture. Layers without art are left out.
ns.MintLayers = {}
for _, layer in ipairs({
    { key = "background", name = "Background" },
    { key = "skin", name = "Skin" },
    { key = "outfit", name = "Outfit" },
    { key = "expression", name = "Expression" },
    { key = "eyes", name = "Eyes" },
    { key = "accessory", name = "Accessory" },
    { key = "headwear", name = "Headwear" },
}) do
    layer.options = ns.MintArt and ns.MintArt[layer.key] or {}
    if #layer.options > 0 then ns.MintLayers[#ns.MintLayers + 1] = layer end
end

-- The texture path of an option in a picture with these traits.
function ns.MintTexture(option, traits)
    if option.perSkin then return option.texture:format(traits.skin or "") end
    return option.texture
end

local function FindOption(layer, id)
    for _, option in ipairs(layer.options) do
        if option.id == id then return option end
    end
end

local function Roll(layer)
    local total = 0
    for _, option in ipairs(layer.options) do total = total + (option.weight or RARITY_WEIGHTS[option.rarity]) end
    local pick = math.random() * total
    for _, option in ipairs(layer.options) do
        pick = pick - (option.weight or RARITY_WEIGHTS[option.rarity])
        if pick <= 0 then return option end
    end
    return layer.options[#layer.options]
end

local function TraitKey(traits)
    local parts = {}
    for i, layer in ipairs(ns.MintLayers) do parts[i] = traits[layer.key] or "" end
    return table.concat(parts, "/")
end

-- Weighted pick among every combination not in owned (only used when random rolls keep hitting owned ones).
local function PickUnowned(owned)
    local combos, total = {}, 0
    local function Walk(i, traits, weight)
        local layer = ns.MintLayers[i]
        if not layer then
            if not owned[TraitKey(traits)] then
                local copy = {}
                for k, v in pairs(traits) do copy[k] = v end
                combos[#combos + 1] = { traits = copy, weight = weight }
                total = total + weight
            end
            return
        end
        for _, option in ipairs(layer.options) do
            traits[layer.key] = option.id
            Walk(i + 1, traits, weight * (option.weight or RARITY_WEIGHTS[option.rarity]))
        end
    end
    Walk(1, {}, 1)
    local pick = math.random() * total
    for _, combo in ipairs(combos) do
        pick = pick - combo.weight
        if pick <= 0 then return combo.traits end
    end
    return combos[#combos].traits
end

-- Chance that a roll scores at least s, for every possible score s (worked out once from the weights).
local atLeast
local function ScoreOdds()
    if atLeast then return atLeast end
    local chance = { [0] = 1 }  -- [score] = chance of exactly that score so far
    for _, layer in ipairs(ns.MintLayers) do
        local total = 0
        for _, option in ipairs(layer.options) do total = total + (option.weight or RARITY_WEIGHTS[option.rarity]) end
        local nextChance = {}
        for score, p in pairs(chance) do
            for _, option in ipairs(layer.options) do
                local s = score + RARITY_SCORE[option.rarity]
                nextChance[s] = (nextChance[s] or 0) + p * (option.weight or RARITY_WEIGHTS[option.rarity]) / total
            end
        end
        chance = nextChance
    end
    local maxScore = 0
    for score in pairs(chance) do maxScore = math.max(maxScore, score) end
    atLeast = {}
    local sum = 0
    for score = maxScore, 0, -1 do
        sum = sum + (chance[score] or 0)
        atLeast[score] = sum
    end
    return atLeast
end

-- Overall rarity from the traits' rarities added up, graded by how few rolls score that high:
-- legendary = top 1.5% of pictures, epic = top 5%, rare = top 17%, uncommon = top 55%, else common.
function ns.MintRarity(traits)
    local score = 0
    for _, layer in ipairs(ns.MintLayers) do
        local option = FindOption(layer, traits[layer.key])
        score = score + (option and RARITY_SCORE[option.rarity] or 0)
    end
    local share = ScoreOdds()[score] or 1
    for _, tier in ipairs(PICTURE_TIERS) do
        if share <= tier[2] + 1e-9 then return tier[1] end
    end
    return RARITY_ORDER[1]
end

-- Traits as display lines: { { layer name, option name, rarity } }.
function ns.MintTraits(traits)
    local lines = {}
    for _, layer in ipairs(ns.MintLayers) do
        local option = FindOption(layer, traits[layer.key])
        if option then lines[#lines + 1] = { layer.name, option.name, option.rarity } end
    end
    return lines
end

-- Rolls and saves a new picture you don't own yet. Returns the mint, or nil and why not.
-- Guild registry: every picture owned by you or a synced friend, as [trait key] = { owner, time }.
-- Owner is nil for your own. Minting never rolls a taken picture.
local function TakenPictures(exceptMint)
    local taken = {}
    for _, mint in ipairs(KillTrackerDB.mints) do
        if mint ~= exceptMint then taken[TraitKey(mint.traits)] = { time = mint.time } end
    end
    for fullName, friend in pairs(KillTrackerFriends or {}) do
        for _, mint in pairs(friend.mints or {}) do
            local key = TraitKey(mint.traits)
            if not taken[key] then taken[key] = { owner = fullName, time = mint.time } end
        end
    end
    return taken
end

-- Rolls a picture nobody in the registry has. Returns traits, or nil if every picture is taken.
local function RollFree(taken)
    local count, possible = 0, 1
    for _ in pairs(taken) do count = count + 1 end
    for _, layer in ipairs(ns.MintLayers) do possible = possible * #layer.options end
    if count >= possible then return end
    for _ = 1, 200 do
        local traits = {}
        for _, layer in ipairs(ns.MintLayers) do traits[layer.key] = Roll(layer).id end
        if not taken[TraitKey(traits)] then return traits end
    end
    -- Few pictures left to find (often rare ones): pick among the remaining ones, still by weight.
    -- Only feasible for small sets; with millions of combinations 200 misses in a row won't happen.
    if possible <= 100000 then return PickUnowned(taken) end
end

-- Rolls and saves a new picture nobody in your guild owns yet. Returns the mint, or nil and why not.
function ns.Mint()
    local db = KillTrackerDB
    local balance, cost = ns.GetPoints().balance, ns.MintCost()
    if balance < cost then
        return nil, ("Not enough points (%d of %d)."):format(balance, cost)
    end
    local traits = RollFree(TakenPictures())
    if not traits then return nil, "Every possible picture is already taken." end
    db.points.spent = db.points.spent + cost
    local mint = { number = #db.mints + 1, traits = traits, time = time(), cost = cost }
    db.mints[#db.mints + 1] = mint
    ns.Touch(mint)  -- syncs it to guildmates
    if ns.AddEvent then ns.AddEvent("M", mint.number) end
    return mint
end

-- Marks your pictures that a friend minted first (earlier time; on a tie, the alphabetically first
-- name) as duplicates: mint.duplicateOf = their name. They get a free reroll.
function ns.UpdateDuplicates()
    local me = ns.MyName()
    for _, mint in ipairs(KillTrackerDB.mints) do
        mint.duplicateOf = nil
        local key = TraitKey(mint.traits)
        for fullName, friend in pairs(KillTrackerFriends or {}) do
            for _, theirs in pairs(friend.mints or {}) do
                if TraitKey(theirs.traits) == key then
                    local name = Ambiguate and Ambiguate(fullName, "short") or fullName
                    if theirs.time < mint.time or (theirs.time == mint.time and name < me) then
                        mint.duplicateOf = name
                    end
                end
            end
        end
    end
end

-- Free reroll of a duplicate: a new picture nobody has, keeping its number.
function ns.RerollMint(mint)
    if not mint.duplicateOf then return nil, "Only duplicates can be rerolled." end
    local traits = RollFree(TakenPictures(mint))
    if not traits then return nil, "Every possible picture is already taken." end
    mint.traits, mint.time, mint.duplicateOf = traits, time(), nil
    ns.Touch(mint)
    return mint
end

-- Draws a picture into canvas (a frame), creating one texture per layer on first use.
function ns.RenderMint(canvas, traits)
    canvas.layers = canvas.layers or {}
    local size = canvas:GetWidth()
    for i, layer in ipairs(ns.MintLayers) do
        local tex = canvas.layers[i]
        if not tex then
            tex = canvas:CreateTexture(nil, "ARTWORK", nil, i - 1)  -- sublevel = stacking order
            canvas.layers[i] = tex
        end
        local option = FindOption(layer, traits[layer.key])
        local texture = option and option.texture and ns.MintTexture(option, traits)
        tex:ClearAllPoints()
        tex:SetVertexColor(1, 1, 1)
        if not option or (not texture and not option.color) then
            tex:Hide()
        else
            local rect = option.rect
            if rect then
                tex:SetPoint("TOPLEFT", canvas, "TOPLEFT", rect[1] * size, -rect[2] * size)
                tex:SetSize(rect[3] * size, rect[4] * size)
            else
                tex:SetAllPoints(canvas)
            end
            if texture then
                tex:SetTexture(texture)
                if option.color then tex:SetVertexColor(unpack(option.color)) end
            else
                tex:SetColorTexture(unpack(option.color))
            end
            tex:Show()
        end
    end
end

-- Pictures whose traits no longer exist (e.g. from the placeholder test set) are removed and refunded.
-- A picture missing a layer added later isn't outdated; it simply has nothing on that layer.
local function RemoveOutdatedMints()
    local db, kept, refund, removed = KillTrackerDB, {}, 0, 0
    for _, mint in ipairs(db.mints) do
        local valid = true
        for _, layer in ipairs(ns.MintLayers) do
            local id = mint.traits[layer.key]
            if id and not FindOption(layer, id) then valid = false end
        end
        if valid then
            kept[#kept + 1] = mint
            if mint.number ~= #kept then mint.number = #kept; ns.Touch(mint) end
        else
            refund = refund + (mint.cost or 100)  -- pictures from before 0.32.0 all cost 100
            removed = removed + 1
        end
    end
    if refund > 0 then
        db.mints = kept
        db.points.spent = math.max(0, db.points.spent - refund)
        ns.Print(("Removed %d test picture(s) made with the old placeholder art; %d points refunded."):format(removed, refund))
    end
end

local loader = CreateFrame("Frame")
loader:RegisterEvent("PLAYER_LOGIN")
loader:SetScript("OnEvent", RemoveOutdatedMints)

StaticPopupDialogs["SOLC_REROLL"] = {
    text = "%s minted this picture first. Reroll it for free?",
    button1 = YES or "Yes",
    button2 = NO or "No",
    OnAccept = function(_, mint)
        local rerolled, reason = ns.RerollMint(mint)
        if not rerolled then
            ns.Print(reason)
            return
        end
        if ns.OnKillsChanged then ns.OnKillsChanged() end
        ns.PlayMintReel(rerolled)
    end,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
}

function ns.ConfirmReroll(mint)
    StaticPopup_Show("SOLC_REROLL", mint.duplicateOf, nil, mint)
end

StaticPopupDialogs["SOLC_MINT"] = {
    text = "Mint a new picture for %d points?",
    button1 = YES or "Yes",
    button2 = NO or "No",
    OnAccept = function()
        local mint, reason = ns.Mint()
        if not mint then
            ns.Print(reason)
            return
        end
        -- Already saved; the reel show (MintReel.lua) reveals it layer by layer and announces it.
        if ns.OnKillsChanged then ns.OnKillsChanged() end
        ns.PlayMintReel(mint)
    end,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
}

function ns.ConfirmMint()
    StaticPopup_Show("SOLC_MINT", ns.MintCost())
end
