-- Pseudo-minting: a picture is a stack of layers (background, skin, outfit, expression, eyes, accessory,
-- headwear). Minting rolls one option per layer, weighted by rarity, and saves only the result in
-- KillTrackerDB.mints = { { number, traits = { [layer key] = option id }, time, claim } }. Pictures are
-- drawn by stacking the chosen layer images; a backend can rebuild the same picture from the traits.
--
-- Art: the options and their textures come from MintArt.lua, generated by tools/convert-art.js from the
-- PNGs in tools/art-source. Options with perSkin have one texture per skin (eyes and mouths drawn in
-- the skin's colour), picked by the picture's skin trait.

local _, ns = ...

-- The price of a mint is a guild setting (Config.lua); each picture remembers what it cost.
function ns.MintCost() return ns.Config("mintCost") end

-- Four rarities; there is no common (uncommon is the everyday tier).
local RARITY_WEIGHTS = { uncommon = 25, rare = 10, epic = 4, legendary = 1 }
ns.MINT_WEIGHTS = RARITY_WEIGHTS
local RARITY_SCORE = { uncommon = 1, rare = 2, epic = 3, legendary = 4 }
ns.MINT_SCORES = RARITY_SCORE
local RARITY_ORDER = { "uncommon", "rare", "epic", "legendary" }
-- A picture's overall rarity: the share of all rolls that score at least as high (see ns.MintRarity).
local PICTURE_TIERS = { { "legendary", 0.015 }, { "epic", 0.05 }, { "rare", 0.17 } }  -- the rest: uncommon
ns.MINT_TIERS = PICTURE_TIERS  -- (these settings are read by the SOLC Puzzle Discord Activity's art build too)

-- Layers from back to front; options { id (never change once released), name, rarity, texture, rect,
-- perSkin } from MintArt.lua. rect = { x, y, width, height } as fractions of the picture places a
-- cropped image; options without one cover the whole picture. Layers without art are left out.
ns.MintLayers = {}
for _, layer in ipairs({
    { key = "background", name = "Background" },
    { key = "skin", name = "Skin" },
    { key = "outfit", name = "Outfit" },
    { key = "expression", name = "Expression" },
    { key = "eyes", name = "Eyes" },
    { key = "accessory", name = "Accessory" },
    { key = "headwear", name = "Headwear" },
}) do
    layer.options = ns.MintArt and ns.MintArt[layer.key] or {}
    if #layer.options > 0 then ns.MintLayers[#ns.MintLayers + 1] = layer end
end

-- The texture path of an option in a picture with these traits.
function ns.MintTexture(option, traits)
    if option.perSkin then return option.texture:format(traits.skin or "") end
    return option.texture
end

local function FindOption(layer, id)
    for _, option in ipairs(layer.options) do
        if option.id == id then return option end
    end
end

local function Roll(layer)
    local total = 0
    for _, option in ipairs(layer.options) do total = total + (option.weight or RARITY_WEIGHTS[option.rarity]) end
    local pick = math.random() * total
    for _, option in ipairs(layer.options) do
        pick = pick - (option.weight or RARITY_WEIGHTS[option.rarity])
        if pick <= 0 then return option end
    end
    return layer.options[#layer.options]
end

local function TraitKey(traits)
    local parts = {}
    for i, layer in ipairs(ns.MintLayers) do parts[i] = traits[layer.key] or "" end
    return table.concat(parts, "/")
end

-- Weighted pick among every combination not in owned (only used when random rolls keep hitting owned ones).
local function PickUnowned(owned)
    local combos, total = {}, 0
    local function Walk(i, traits, weight)
        local layer = ns.MintLayers[i]
        if not layer then
            if not owned[TraitKey(traits)] then
                local copy = {}
                for k, v in pairs(traits) do copy[k] = v end
                combos[#combos + 1] = { traits = copy, weight = weight }
                total = total + weight
            end
            return
        end
        for _, option in ipairs(layer.options) do
            traits[layer.key] = option.id
            Walk(i + 1, traits, weight * (option.weight or RARITY_WEIGHTS[option.rarity]))
        end
    end
    Walk(1, {}, 1)
    local pick = math.random() * total
    for _, combo in ipairs(combos) do
        pick = pick - combo.weight
        if pick <= 0 then return combo.traits end
    end
    return combos[#combos].traits
end

-- Chance that a roll scores at least s, for every possible score s (worked out once from the weights).
local atLeast
local function ScoreOdds()
    if atLeast then return atLeast end
    local chance = { [0] = 1 }  -- [score] = chance of exactly that score so far
    for _, layer in ipairs(ns.MintLayers) do
        local total = 0
        for _, option in ipairs(layer.options) do total = total + (option.weight or RARITY_WEIGHTS[option.rarity]) end
        local nextChance = {}
        for score, p in pairs(chance) do
            for _, option in ipairs(layer.options) do
                local s = score + RARITY_SCORE[option.rarity]
                nextChance[s] = (nextChance[s] or 0) + p * (option.weight or RARITY_WEIGHTS[option.rarity]) / total
            end
        end
        chance = nextChance
    end
    local maxScore = 0
    for score in pairs(chance) do maxScore = math.max(maxScore, score) end
    atLeast = {}
    local sum = 0
    for score = maxScore, 0, -1 do
        sum = sum + (chance[score] or 0)
        atLeast[score] = sum
    end
    return atLeast
end

-- Overall rarity from the traits' rarities added up, graded by how few rolls score that high:
-- legendary = top 1.5% of pictures, epic = top 5%, rare = top 17%, else uncommon.
function ns.MintRarity(traits)
    local score = 0
    for _, layer in ipairs(ns.MintLayers) do
        local option = FindOption(layer, traits[layer.key])
        score = score + (option and RARITY_SCORE[option.rarity] or 0)
    end
    local share = ScoreOdds()[score] or 1
    for _, tier in ipairs(PICTURE_TIERS) do
        if share <= tier[2] + 1e-9 then return tier[1] end
    end
    return RARITY_ORDER[1]
end

-- Traits as display lines: { { layer name, option name, rarity } }.
function ns.MintTraits(traits)
    local lines = {}
    for _, layer in ipairs(ns.MintLayers) do
        local option = FindOption(layer, traits[layer.key])
        if option then lines[#lines + 1] = { layer.name, option.name, option.rarity } end
    end
    return lines
end

-- Rolls and saves a new picture you don't own yet. Returns the mint, or nil and why not.
-- Guild registry: every picture owned by you or a synced friend, as [trait key] = { owner, time }.
-- Owner is nil for your own. Minting never rolls a taken picture.
local function TakenPictures(exceptMint)
    local taken = {}
    for _, mint in ipairs(KillTrackerDB.mints) do
        if mint ~= exceptMint then taken[TraitKey(mint.traits)] = { time = mint.time } end
    end
    for fullName, friend in pairs(KillTrackerFriends or {}) do
        for _, mint in pairs(friend.mints or {}) do
            local key = TraitKey(mint.traits)
            if not taken[key] then taken[key] = { owner = fullName, time = mint.time } end
        end
    end
    return taken
end

-- Rolls a picture nobody in the registry has. Returns traits, or nil if every picture is taken.
local function RollFree(taken)
    local count, possible = 0, 1
    for _ in pairs(taken) do count = count + 1 end
    for _, layer in ipairs(ns.MintLayers) do possible = possible * #layer.options end
    if count >= possible then return end
    for _ = 1, 200 do
        local traits = {}
        for _, layer in ipairs(ns.MintLayers) do traits[layer.key] = Roll(layer).id end
        if not taken[TraitKey(traits)] then return traits end
    end
    -- Few pictures left to find (often rare ones): pick among the remaining ones, still by weight.
    -- Only feasible for small sets; with millions of combinations 200 misses in a row won't happen.
    if possible <= 100000 then return PickUnowned(taken) end
end

-- Rolls and saves a new picture nobody in your guild owns yet. Returns the mint, or nil and why not.
function ns.Mint()
    local db = KillTrackerDB
    local balance, cost = ns.GetPoints().balance, ns.MintCost()
    if balance < cost then
        return nil, ("Not enough points (%d of %d)."):format(balance, cost)
    end
    local traits = RollFree(TakenPictures())
    if not traits then return nil, "Every possible picture is already taken." end
    db.points.spent = db.points.spent + cost
    local mint = { number = ns.NextMintNumber(), traits = traits, time = time(), cost = cost }
    db.mints[#db.mints + 1] = mint
    ns.Touch(mint)  -- syncs it to guildmates
    if ns.AddEvent then ns.AddEvent("M", mint.number) end
    return mint
end

-- The number for your next picture: above every number used so far, including pictures given away
-- (KillTrackerDB.removedMints), so a number never means two different pictures.
function ns.NextMintNumber()
    local db = KillTrackerDB
    local highest = 0
    for _, mint in ipairs(db.mints) do highest = math.max(highest, mint.number) end
    for number in pairs(db.removedMints or {}) do highest = math.max(highest, number) end
    return highest + 1
end

-- Gives away your picture (won in a puzzle race, see SOLC Puzzle): removes it from your pictures and your
-- showcase, and records the removal so guildmates drop it too (Sync.lua). Returns its traits, or nil.
function ns.RemoveMint(number)
    local db = KillTrackerDB
    for i, mint in ipairs(db.mints) do
        if mint.number == number then
            table.remove(db.mints, i)
            local showcase = db.showcase
            if showcase then
                for j, n in ipairs(showcase.numbers) do
                    if n == number then table.remove(showcase.numbers, j) ns.Touch(showcase) break end
                end
            end
            db.removedMints = db.removedMints or {}  -- [number] = change number of the removal
            db.seq = db.seq + 1
            db.removedMints[number] = db.seq
            if ns.OnKillsChanged then ns.OnKillsChanged() end
            return mint.traits
        end
    end
end

-- Adds a picture you won (from another player or an officer's mint battle) under your next number.
-- mintedAt: when it was first minted (kept, so it isn't taken for a later duplicate); now if new.
function ns.AddWonMint(traits, from, mintedAt)
    local db = KillTrackerDB
    local copy = {}
    for key, id in pairs(traits) do copy[key] = id end
    local mint = { number = ns.NextMintNumber(), traits = copy, time = mintedAt or time(), cost = 0, wonFrom = from }
    db.mints[#db.mints + 1] = mint
    ns.Touch(mint)  -- syncs it to guildmates
    if ns.AddEvent then ns.AddEvent("W", mint.number, from) end
    if ns.OnKillsChanged then ns.OnKillsChanged() end
    return mint
end

-- Rolls a picture nobody in the guild owns yet, without saving it (for an officer's mint battle).
function ns.RollFreePicture()
    return RollFree(TakenPictures())
end

-- Marks your pictures that a friend minted first (earlier time; on a tie, the alphabetically first
-- name) as duplicates: mint.duplicateOf = their name. They get a free reroll.
function ns.UpdateDuplicates()
    local me = ns.MyName()
    for _, mint in ipairs(KillTrackerDB.mints) do
        mint.duplicateOf = nil
        local key = TraitKey(mint.traits)
        for fullName, friend in pairs(KillTrackerFriends or {}) do
            for _, theirs in pairs(friend.mints or {}) do
                if TraitKey(theirs.traits) == key then
                    local name = Ambiguate and Ambiguate(fullName, "short") or fullName
                    if theirs.time < mint.time or (theirs.time == mint.time and name < me) then
                        mint.duplicateOf = name
                    end
                end
            end
        end
    end
end

-- Free reroll of a duplicate: a new picture nobody has, keeping its number.
function ns.RerollMint(mint)
    if not mint.duplicateOf then return nil, "Only duplicates can be rerolled." end
    local traits = RollFree(TakenPictures(mint))
    if not traits then return nil, "Every possible picture is already taken." end
    mint.traits, mint.time, mint.duplicateOf = traits, time(), nil
    ns.Touch(mint)
    return mint
end

-- Options drawn in front of every layer instead of in their own layer's place: face accessories that a hat
-- would otherwise cover (the eye mask sits where hats go). Here, not in MintArt.lua, which is generated.
local IN_FRONT = { eye_mask_pushed_up = true, monocle = true }
ns.MINT_IN_FRONT = IN_FRONT
local FRONT_SUBLEVEL = 7  -- the top of the ARTWORK draw layer

-- A picture's layers in drawing order, back to front: { { layer key, option id } }, with IN_FRONT options
-- last, as RenderMint stacks them (the paint game builds its colours the same way).
function ns.MintDrawOrder(traits)
    local order, front = {}, {}
    for _, layer in ipairs(ns.MintLayers) do
        local option = FindOption(layer, traits[layer.key])
        if option then
            local list = IN_FRONT[option.id] and front or order
            list[#list + 1] = { key = layer.key, id = option.id, perSkin = option.perSkin }
        end
    end
    for _, entry in ipairs(front) do order[#order + 1] = entry end
    return order
end

-- Draws a picture into canvas (a frame), creating one texture per layer on first use.
function ns.RenderMint(canvas, traits)
    canvas.layers = canvas.layers or {}
    local size = canvas:GetWidth()
    for i, layer in ipairs(ns.MintLayers) do
        local tex = canvas.layers[i]
        if not tex then
            tex = canvas:CreateTexture(nil, "ARTWORK", nil, i - 1)  -- sublevel = stacking order
            canvas.layers[i] = tex
        end
        local option = FindOption(layer, traits[layer.key])
        local texture = option and option.texture and ns.MintTexture(option, traits)
        tex:SetDrawLayer("ARTWORK", option and IN_FRONT[option.id] and FRONT_SUBLEVEL or i - 1)
        tex:ClearAllPoints()
        tex:SetVertexColor(1, 1, 1)
        if not option or (not texture and not option.color) then
            tex:Hide()
        else
            local rect = option.rect
            if rect then
                tex:SetPoint("TOPLEFT", canvas, "TOPLEFT", rect[1] * size, -rect[2] * size)
                tex:SetSize(rect[3] * size, rect[4] * size)
            else
                tex:SetAllPoints(canvas)
            end
            if texture then
                tex:SetTexture(texture)
                if option.color then tex:SetVertexColor(unpack(option.color)) end
            else
                tex:SetColorTexture(unpack(option.color))
            end
            tex:Show()
        end
    end
end

-- Pictures whose traits no longer exist (e.g. from the placeholder test set) are removed and refunded.
-- A picture missing a layer added later isn't outdated; it simply has nothing on that layer.
local function RemoveOutdatedMints()
    local db, kept, refund, removed = KillTrackerDB, {}, 0, 0
    for _, mint in ipairs(db.mints) do
        local valid = true
        for _, layer in ipairs(ns.MintLayers) do
            local id = mint.traits[layer.key]
            if id and not FindOption(layer, id) then valid = false end
        end
        if valid then
            kept[#kept + 1] = mint
            if mint.number ~= #kept then mint.number = #kept; ns.Touch(mint) end
        else
            refund = refund + (mint.cost or 100)  -- pictures from before 0.32.0 all cost 100
            removed = removed + 1
        end
    end
    if refund > 0 then
        db.mints = kept
        db.points.spent = math.max(0, db.points.spent - refund)
        ns.Print(("Removed %d test picture(s) made with the old placeholder art; %d points refunded."):format(removed, refund))
    end
end

local loader = CreateFrame("Frame")
loader:RegisterEvent("PLAYER_LOGIN")
loader:SetScript("OnEvent", RemoveOutdatedMints)

StaticPopupDialogs["SOLC_REROLL"] = {
    text = "%s minted this picture first. Reroll it for free?",
    button1 = YES or "Yes",
    button2 = NO or "No",
    OnAccept = function(_, mint)
        local rerolled, reason = ns.RerollMint(mint)
        if not rerolled then
            ns.Print(reason)
            return
        end
        if ns.OnKillsChanged then ns.OnKillsChanged() end
        ns.PlayMintReel(rerolled)
    end,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
}

function ns.ConfirmReroll(mint)
    StaticPopup_Show("SOLC_REROLL", mint.duplicateOf, nil, mint)
end

StaticPopupDialogs["SOLC_MINT"] = {
    text = "Mint a new picture for %d points?",
    button1 = YES or "Yes",
    button2 = NO or "No",
    OnAccept = function()
        local mint, reason = ns.Mint()
        if not mint then
            ns.Print(reason)
            return
        end
        -- Already saved; the reel show (MintReel.lua) reveals it layer by layer and announces it.
        if ns.OnKillsChanged then ns.OnKillsChanged() end
        ns.PlayMintReel(mint)
    end,
    timeout = 0,
    whileDead = true,
    hideOnEscape = true,
}

function ns.ConfirmMint()
    StaticPopup_Show("SOLC_MINT", ns.MintCost())
end

-- Showcase: up to SHOWCASE_SIZE of your pictures on your Overview, synced to guildmates (Sync.lua):
-- KillTrackerDB.showcase = { numbers = { picture number, ... }, backdrop = background option id, seq }.

ns.SHOWCASE_SIZE = 3

local function Showcase()
    local db = KillTrackerDB
    db.showcase = db.showcase or { numbers = {} }
    return db.showcase
end

function ns.IsShowcased(number)
    for _, n in ipairs(Showcase().numbers) do
        if n == number then return true end
    end
    return false
end

-- Adds your picture to the showcase, or takes it off. Returns false and a reason if the showcase is full.
function ns.ToggleShowcase(mint)
    local showcase = Showcase()
    if ns.IsShowcased(mint.number) then
        for i, n in ipairs(showcase.numbers) do
            if n == mint.number then table.remove(showcase.numbers, i) break end
        end
    elseif #showcase.numbers >= ns.SHOWCASE_SIZE then
        return false, ("Your showcase is full (%d pictures). Take one off first."):format(ns.SHOWCASE_SIZE)
    else
        showcase.numbers[#showcase.numbers + 1] = mint.number
    end
    ns.Touch(showcase)
    if ns.OnKillsChanged then ns.OnKillsChanged() end
    return true
end

-- The background behind your 3D model on the Overview: one from a picture you own, chosen by right-clicking
-- the model; showcase.backdrop = its option id, synced with the showcase.

-- The backgrounds on your pictures, each once, as options (id, name, rarity, texture), rarest first.
function ns.OwnedBackgrounds()
    local layer
    for _, l in ipairs(ns.MintLayers) do
        if l.key == "background" then layer = l end
    end
    local seen, list = {}, {}
    for _, mint in ipairs(layer and KillTrackerDB.mints or {}) do
        local id = mint.traits and mint.traits.background
        local option = id and not seen[id] and FindOption(layer, id)
        if option then
            seen[id] = true
            list[#list + 1] = option
        end
    end
    table.sort(list, function(a, b)
        if a.rarity ~= b.rarity then return (RARITY_SCORE[a.rarity] or 0) > (RARITY_SCORE[b.rarity] or 0) end
        return a.name < b.name
    end)
    return list
end

-- Sets (option id) or clears (nil) the background behind your model.
function ns.SetModelBackdrop(id)
    local showcase = Showcase()
    if showcase.backdrop == id then return end
    showcase.backdrop = id
    ns.Touch(showcase)
    if ns.OnKillsChanged then ns.OnKillsChanged() end
end

-- The background behind someone's model, as an option: yours (key nil; only while you still own a picture with
-- it) or a synced guildmate's. nil for none.
function ns.GetModelBackdrop(key)
    local source = key and KillTrackerFriends[key] or KillTrackerDB
    local id = source and source.showcase and source.showcase.backdrop
    if not id then return nil end
    if key then
        for _, l in ipairs(ns.MintLayers) do
            if l.key == "background" then return FindOption(l, id) end
        end
        return nil
    end
    for _, option in ipairs(ns.OwnedBackgrounds()) do
        if option.id == id then return option end
    end
end

-- Someone's showcased pictures, in order: yours (key nil) or a synced guildmate's. Pictures that no
-- longer exist are skipped.
function ns.GetShowcase(key)
    local source = key and KillTrackerFriends[key] or KillTrackerDB
    local numbers = source and source.showcase and source.showcase.numbers or {}
    local pictures = {}
    for _, number in ipairs(numbers) do
        local mint
        if key then
            mint = source.mints and source.mints[number]
        else
            for _, m in ipairs(source.mints or {}) do
                if m.number == number then mint = m end
            end
        end
        if mint then pictures[#pictures + 1] = mint end
    end
    return pictures
end
