-- Generated by tools/overview-layout.js - don't edit; change the layout there and rerun it.
-- The wooden window frame (UI.lua) and the new Overview's inside and character card (OverviewCard.lua), in window
-- pixels (from its top-left, y down). Pieces: { x, y (centre), w, h, tilt (degrees clockwise), texture
-- (Media/Overview), shade, coords (texture crop) } in drawing order; areas: { x, y (centre), w, h }; spots:
-- { x, y (centre), size }.

local _, ns = ...

ns.OverviewLayout = {
    frame = {
        { x = 198, y = 303, w = 60, h = 526, tilt = 0, texture = "FrameLeft" },
        { x = 932, y = 303, w = 64, h = 526, tilt = 0, texture = "FrameRight" },
        { x = 566, y = 594, w = 796, h = 58, tilt = 0, texture = "FrameBottom" },
    },
    inner = { left = 206, right = 923, top = 44, bottom = 588 },
    page = {
        { x = 560.526, y = 298.909, w = 753.651, h = 680.418, tilt = 0, texture = "Inside", coords = { 0, 0.794, 0, 0.717 } },
    },
    spineCaps = {
        { x = 563.77, y = 22.2, w = 92.7, h = 82.503, tilt = 0, texture = "CapTop", coords = { 0, 0.781, 0, 0.695 } },
        { x = 564.234, y = 590.451, w = 75.087, h = 60.255, tilt = 0, texture = "CapBottom", coords = { 0, 0.633, 0, 0.508 } },
    },
    card = {
        label = { x = 758.718, y = 83.845, w = 172.422, h = 32.816 },
        arrows = { { x = 647.478, y = 85.375, w = 50.058, h = 41.993 }, { x = 870.422, y = 84.587, w = 50.985, h = 41.715 } },
        arrowGlyphs = { { x = 644.883, y = 85.421, w = 23.175, h = 27.81 }, { x = 872.739, y = 84.309, w = 27.81, h = 32.445 } },
        photo = { x = 761.082, y = 278.237, w = 243.152, h = 281.808 },
        icons = {
            race = { x = 668.243, y = 168.851, size = 43.569 },
            gender = { x = 668.058, y = 215.479, size = 42.642 },
            class = { x = 847.247, y = 172.188, size = 48.204 },
            professions = { { x = 848.637, y = 338.77, size = 48.204 }, { x = 848.637, y = 391.331, size = 48.204 } },
            secondary = { { x = 658.788, y = 349.152, size = 38.934 }, { x = 682.704, y = 373.533, size = 38.934 }, { x = 660.363, y = 396.708, size = 38.934 } },
        },
        signature = { x = 761.221, y = 458.538, w = 203.94, h = 50.985 },
    },
}
