-- Generated by tools/overview-layout.js - don't edit; change the layout there and rerun it.
-- The wooden window frame (UI.lua) and the new Overview (OverviewCard.lua), in window pixels (from its top-left,
-- y down). Pieces: { x, y (centre), w, h, tilt (degrees clockwise), texture (Media/Overview), coords (texture
-- crop) } in drawing order; areas: { x, y (centre), w, h }; spots: { x, y (centre), size }.

local _, ns = ...

ns.OverviewLayout = {
    frame = {
        { x = 198, y = 303, w = 60, h = 526, tilt = 0, texture = "FrameLeft" },
        { x = 932, y = 303, w = 64, h = 526, tilt = 0, texture = "FrameRight" },
        { x = 566, y = 594, w = 796, h = 58, tilt = 0, texture = "FrameBottom" },
    },
    inner = { left = 206, right = 923, top = 44, bottom = 588 },
    page = {
        { x = 560.331, y = 319.268, w = 756.448, h = 561.027, tilt = 0, texture = "Inside", coords = { 0, 0.794, 0, 0.587 } },
    },
    spineCaps = {
        { x = 564.052, y = 21.485, w = 90.253, h = 81.214, tilt = 0, texture = "CapTop", coords = { 0, 0.758, 0, 0.68 } },
        { x = 564.983, y = 594.18, w = 71.644, h = 59.743, tilt = 0, texture = "CapBottom", coords = { 0, 0.602, 0, 0.5 } },
    },
    stats = {
        boards = { { x = 263.985, y = 102.698, w = 91.183, h = 94.282 }, { x = 372.382, y = 100.365, w = 92.114, h = 91.482 }, { x = 486.826, y = 105.499, w = 92.114, h = 90.548 } },
        numbers = { { x = 264.916, y = 128.369, w = 74.435, h = 16.803 }, { x = 372.847, y = 129.303, w = 74.435, h = 16.803 }, { x = 486.361, y = 129.303, w = 74.435, h = 16.803 } },
    },
    -- The showcase's small polaroids, in drawing order: slot (which showcase picture), centre, tilt, nail. The
    -- base's parts are offsets from its centre before turning.
    polaroids = {
        { slot = 2, x = 416.019, y = 257.471, tilt = -3.75, nail = { x = 403.086, y = 173.177 } },
        { slot = 1, x = 280.826, y = 289.023, tilt = -2.6, nail = { x = 269.568, y = 205.849 } },
        { slot = 3, x = 514.041, y = 304.799, tilt = 3.4, nail = { x = 523.113, y = 215.184 } },
    },
    polaroid = { w = 146.117, h = 179.974,
        photo = { x = 0, y = -18.71, size = 112.261 },
        caption = { x = 0, y = 57.021, w = 124.734, h = 33.856 },
        date = { x = 67.713, y = 80.186 },
        nail = 9.32 },
    feed = {
        left = 210.02, top = 419.618, width = 333.098,
        rowHeight = 28.005, rows = 5, textSize = 13, timeSize = 11,
        rowLeft = 186.759, rowRight = 560.796,
        spine = { x = 560.796, y = 508.299, w = 39.079, h = 182.964, tilt = 0, texture = "SpineCut", coords = { 0, 0.656, 0, 0.766 } },
    },
    card = {
        label = { x = 759.585, y = 86.035, w = 173.713, h = 34.259 },
        arrows = { { x = 647.141, y = 86.035, w = 51.174, h = 40.42 }, { x = 871.237, y = 86.035, w = 49.592, h = 40.42 } },
        arrowGlyphs = { { x = 644.861, y = 86.035, w = 24.843, h = 24.924 }, { x = 873.564, y = 85.289, w = 26.331, h = 29.592 } },
        photo = { x = 761.678, y = 280.061, w = 243.031, h = 280.98 },
        icons = {
            race = { x = 668.076, y = 169.723, size = 42.87 },
            gender = { x = 668.448, y = 217.051, size = 42.87 },
            class = { x = 850.349, y = 175.23, size = 48.462 },
            professions = { { x = 850.349, y = 341.205, size = 48.462 }, { x = 850.349, y = 393.293, size = 48.462 } },
            secondary = { { x = 658.771, y = 352.126, size = 37.279 }, { x = 682.87, y = 375.464, size = 37.279 }, { x = 660.353, y = 400.295, size = 37.279 } },
        },
        signature = { x = 762.701, y = 461.018, w = 201.533, h = 49.755 },
        gear = { x = 755.398, y = 541.158, w = 151.011, h = 60.677 },
    },
}
