-- Generated by tools/convert-skeleton.js - don't edit; change it and rerun it.
-- The window's skeleton (UI.lua): its size, the pieces on every page { file (Media/Skeleton), x, y (top-left, from the
-- window's top-left, y down), w, h, coords (texture crop) } in drawing order, the page area between them, the
-- logo's drag handles (rows of cells, runs of opaque ones) and the beams a page can place (ns.UI.Beam).

local _, ns = ...

ns.SkeletonLayout = {
    width = 1132, height = 778,
    pieces = {
        { file = "PostLeft", x = 184, y = 120, w = 64, h = 604, coords = { 0, 1, 0, 0.5898 } },
        { file = "PostRight", x = 1049, y = 120, w = 64, h = 604, coords = { 0, 1, 0, 0.5898 } },
        { file = "Bottom", x = 184, y = 720, w = 929, h = 57, coords = { 0, 0.9072, 0, 0.8906 } },
        { file = "TopBeam", x = 232, y = 88, w = 900, h = 64, coords = { 0, 0.8789, 0, 1 } },
        { file = "Logo", x = 0, y = 0, w = 256, h = 223, coords = { 0, 1, 0, 0.8711 } },
    },
    inner = { left = 237, right = 1064, top = 146, bottom = 730 },
    topBeam = { left = 232, right = 1132, top = 94, bottom = 146 },
    logoSignBottom = 174,  -- the "Leisure Club" sign's bottom edge, where the sidebar's top button hangs
    logoMask = { cell = 8, rows = {
        {  },
        {  },
        {  },
        { { 16, 19 } },
        { { 10, 19 } },
        { { 9, 22 } },
        { { 5, 5 }, { 8, 23 } },
        { { 3, 24 }, { 26, 29 } },
        { { 3, 29 } },
        { { 2, 29 } },
        { { 2, 29 } },
        { { 3, 29 } },
        { { 2, 32 } },
        { { 2, 32 } },
        { { 2, 32 } },
        { { 2, 32 } },
        { { 2, 32 } },
        { { 2, 32 } },
        { { 2, 29 } },
        { { 3, 29 } },
        { { 3, 29 } },
        { { 3, 29 } },
        { { 4, 6 }, { 26, 29 } },
        { { 5, 5 }, { 26, 27 } },
        {  },
        {  },
        {  },
        {  },
    } },
    beams = {
        cross = { upright = false, thick = 46, cap = 64, tile = 256, files = { "CrossLeft", "CrossRight", "CrossTile" }, coords = { { 0, 1, 0, 0.7188 }, { 0, 1, 0, 0.7188 }, { 0, 1, 0, 0.7188 } } },
        middle = { upright = true, thick = 47, cap = 56, tile = 512, files = { "MiddleTop", "MiddleBottom", "MiddleTile" }, coords = { { 0, 0.7344, 0, 0.875 }, { 0, 0.7344, 0, 0.875 }, { 0, 0.7344, 0, 1 } } },
    },
}
