-- The paint game: copy a picture onto a size x size canvas (ns.PAINT_SIZES) with a palette of its own main
-- colours, against the clock. The picture's colours come from ns.PaintGrids (PaintData.lua, generated by
-- tools/paint-colors.js), stacked in the picture's drawing order. Everything here is deterministic, so two
-- players painting the same picture get the same target, palette and scoring.

local _, ns = ...

ns.PAINT_SIZES = { 16, 24 }
ns.PAINT_TIMES = { 30, 60, 90, 120, 180 }  -- seconds to paint, chosen per game
ns.DEFAULT_PAINT_TIME = 60
local PALETTE_SIZE = 12
local BLANK = { 0.12, 0.12, 0.12 }  -- an unpainted cell
local CLOSE = 0.35  -- colour distance (0-1) at which a cell scores nothing

-- Target -----------------------------------------------------------------------------------------------------

local CHARS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/"
local VALUE = {}
for i = 1, #CHARS do VALUE[CHARS:sub(i, i)] = i - 1 end

-- A grid string as a list of cells { r, g, b, a } (0-1), or false for a fully transparent cell.
local decoded = {}
local function Decode(text, cells)
    if decoded[text] then return decoded[text] end
    local list, i = {}, 1
    while i <= #text do
        local c = text:sub(i, i)
        if c == "~" then
            for _ = 1, VALUE[text:sub(i + 1, i + 1)] + 1 do list[#list + 1] = false end
            i = i + 2
        else
            list[#list + 1] = { VALUE[c] / 63, VALUE[text:sub(i + 1, i + 1)] / 63, VALUE[text:sub(i + 2, i + 2)] / 63,
                VALUE[text:sub(i + 3, i + 3)] / 63 }
            i = i + 4
        end
    end
    for j = #list + 1, cells do list[j] = false end
    decoded[text] = list
    return list
end

-- The picture as size*size cells { r, g, b }: its layers' grids stacked back to front, as the picture is drawn; each
-- layer in its edition (style: the picture's, SOLC.LayerEdition) where it has grids for it.
function ns.PaintTarget(traits, size, style)
    local cells = size * size
    local target = {}
    for i = 1, cells do target[i] = { 0, 0, 0 } end
    local grids = ns.PaintGrids and ns.PaintGrids[size]
    if not grids then return target end
    for _, layer in ipairs(SOLC.PictureLayers(traits)) do
        local edition = style and SOLC.LayerEdition and SOLC.LayerEdition(style, layer.key)
        local editionGrids = edition and ns.PaintEditionGrids and ns.PaintEditionGrids[edition] and ns.PaintEditionGrids[edition][size]
        local entry = editionGrids and editionGrids[layer.key] and editionGrids[layer.key][layer.id]
        if not entry then entry = grids[layer.key] and grids[layer.key][layer.id] end
        if type(entry) == "table" then entry = entry[traits.skin or ""] end
        if type(entry) == "string" then
            for i, cell in ipairs(Decode(entry, cells)) do
                if cell then
                    local t, a = target[i], cell[4]
                    t[1], t[2], t[3] = t[1] + (cell[1] - t[1]) * a, t[2] + (cell[2] - t[2]) * a, t[3] + (cell[3] - t[3]) * a
                end
            end
        end
    end
    return target
end

local function Distance(a, b)
    local dr, dg, db = a[1] - b[1], a[2] - b[2], a[3] - b[3]
    return math.sqrt((dr * dr * 2 + dg * dg * 4 + db * db * 3) / 9)  -- 0-1, weighted towards how eyes see
end

-- Palette ----------------------------------------------------------------------------------------------------

-- The picture's PALETTE_SIZE main colours (k-means from evenly spread starting colours), darkest first.
function ns.PaintPalette(target)
    -- Start from the most distinct colours: repeatedly the cell farthest from every colour picked so far.
    local centers = { target[1] }
    while #centers < PALETTE_SIZE do
        local best, bestDistance = nil, -1
        for _, cell in ipairs(target) do
            local nearest = math.huge
            for _, c in ipairs(centers) do nearest = math.min(nearest, Distance(cell, c)) end
            if nearest > bestDistance then best, bestDistance = cell, nearest end
        end
        if bestDistance <= 0.01 then break end  -- fewer distinct colours than that
        centers[#centers + 1] = best
    end
    for i, c in ipairs(centers) do centers[i] = { c[1], c[2], c[3] } end
    for _ = 1, 8 do
        local sums = {}
        for i = 1, #centers do sums[i] = { 0, 0, 0, 0 } end
        for _, cell in ipairs(target) do
            local nearest, index = math.huge, 1
            for i, c in ipairs(centers) do
                local d = Distance(cell, c)
                if d < nearest then nearest, index = d, i end
            end
            local s = sums[index]
            s[1], s[2], s[3], s[4] = s[1] + cell[1], s[2] + cell[2], s[3] + cell[3], s[4] + 1
        end
        for i, s in ipairs(sums) do
            if s[4] > 0 then centers[i] = { s[1] / s[4], s[2] / s[4], s[3] / s[4] } end
        end
    end
    table.sort(centers, function(a, b) return a[1] + a[2] + a[3] < b[1] + b[2] + b[3] end)
    return centers
end

-- Score ------------------------------------------------------------------------------------------------------

local function CellScore(painted, target)
    return math.max(0, 1 - Distance(painted, target) / CLOSE)
end

-- How close the painting is, 0-100: per cell how near its colour is to the picture's, compared with the best
-- painting the palette allows (so 100 is possible).
function ns.PaintScore(cells, target, palette)
    local got, best = 0, 0
    for i, t in ipairs(target) do
        got = got + CellScore(cells[i], t)
        local top = 0
        for _, c in ipairs(palette) do top = math.max(top, CellScore(c, t)) end
        best = best + top
    end
    if best <= 0 then return 0 end
    return math.min(100, got / best * 100)
end

-- Canvas -----------------------------------------------------------------------------------------------------

-- A canvas in parent, about pixels across. canvas:Start(size, palette) clears it for painting and records
-- every change (canvas.recording, see ns.SavePainting); canvas:Stop() ends painting. canvas.cells = { {r,g,b} }
-- as painted (for scoring), canvas.ids = palette index per cell (0 = blank). Left click / drag paints with the
-- chosen colour and tool; right click picks up a colour from the canvas (canvas.OnPick(index) after that).
-- canvas:ShowPainting(painting) shows a saved one; canvas:Replay(painting, speed, onDone) plays it back.
function ns.CreateCanvas(parent, pixels)
    local canvas = CreateFrame("Frame", nil, parent, "BackdropTemplate")
    canvas:SetSize(pixels + 8, pixels + 8)
    canvas:SetBackdrop({ bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
        edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", edgeSize = 12,
        insets = { left = 3, right = 3, top = 3, bottom = 3 } })
    canvas:SetBackdropColor(0, 0, 0, 0.9)
    canvas:EnableMouse(true)

    local size, cellSize, textures, palette, active, startedAt, replay
    local sets = {}  -- [size] = textures
    canvas.color, canvas.brush, canvas.tool = 1, 1, "brush"  -- palette index, brush width in cells, brush | fill

    local function Textures(n)
        if sets[n] then return sets[n] end
        local list = {}
        local px = pixels / n
        for i = 1, n * n do
            local row, col = math.floor((i - 1) / n), (i - 1) % n
            local t = canvas:CreateTexture(nil, "ARTWORK")
            t:SetSize(px, px)
            t:SetPoint("TOPLEFT", 4 + col * px, -4 - row * px)
            t:Hide()
            list[i] = t
        end
        sets[n] = list
        return list
    end

    -- Switches to a canvas size, hiding the other size's cells.
    local function Use(newSize, newPalette)
        if textures and newSize ~= size then
            for _, t in ipairs(textures) do t:Hide() end
        end
        size, cellSize, palette = newSize, pixels / newSize, newPalette
        textures = Textures(size)
        for _, t in ipairs(textures) do t:Show() end
    end

    -- Colours cell i with palette index id (0 = blank); records it while painting.
    local function SetCell(i, id, record)
        if canvas.ids[i] == id then return end
        local color = id == 0 and BLANK or palette[id]
        canvas.ids[i], canvas.cells[i] = id, color
        textures[i]:SetColorTexture(color[1], color[2], color[3])
        if record then
            local rec = canvas.recording
            rec[#rec + 1] = { t = GetTime() - startedAt, i = i, id = id }
        end
    end

    local function Clear()
        canvas.ids, canvas.cells = {}, {}
        for i = 1, size * size do
            canvas.ids[i] = -1  -- so the blank below is set
            SetCell(i, 0)
        end
    end

    -- The cell under the cursor (index), or nil.
    local function CellAtCursor()
        local scale = canvas:GetEffectiveScale()
        local x, y = GetCursorPosition()
        x, y = x / scale - canvas:GetLeft() - 4, canvas:GetTop() - y / scale - 4
        local col, row = math.floor(x / cellSize), math.floor(y / cellSize)
        if col < 0 or row < 0 or col >= size or row >= size then return end
        return row * size + col + 1, row, col
    end

    local function Brush(row, col)
        local from = -math.floor((canvas.brush - 1) / 2)
        for dr = from, from + canvas.brush - 1 do
            for dc = from, from + canvas.brush - 1 do
                local r, c = row + dr, col + dc
                if r >= 0 and c >= 0 and r < size and c < size then SetCell(r * size + c + 1, canvas.color, true) end
            end
        end
    end

    -- Fills the area of cells with the same colour as the clicked one.
    local function Fill(start)
        local id, old = canvas.color, canvas.ids[start]
        if old == id then return end
        local stack, seen = { start }, { [start] = true }
        while #stack > 0 do
            local i = table.remove(stack)
            SetCell(i, id, true)
            local row, col = math.floor((i - 1) / size), (i - 1) % size
            local neighbours = {}  -- built one by one: a false in a list literal would stop ipairs early
            if col > 0 then neighbours[#neighbours + 1] = i - 1 end
            if col < size - 1 then neighbours[#neighbours + 1] = i + 1 end
            if row > 0 then neighbours[#neighbours + 1] = i - size end
            if row < size - 1 then neighbours[#neighbours + 1] = i + size end
            for _, n in ipairs(neighbours) do
                if not seen[n] and canvas.ids[n] == old then
                    seen[n] = true
                    stack[#stack + 1] = n
                end
            end
        end
    end

    canvas:SetScript("OnMouseDown", function(self, button)
        if not active then return end
        local i, row, col = CellAtCursor()
        if not i then return end
        if button == "RightButton" then  -- pick up a colour
            local id = self.ids[i]
            if id and id > 0 then
                self.color = id
                if self.OnPick then self.OnPick(id) end
            end
        elseif self.tool == "fill" then
            Fill(i)
        else
            self.painting = true
            Brush(row, col)
        end
    end)
    canvas:SetScript("OnMouseUp", function(self) self.painting = false end)
    canvas:SetScript("OnUpdate", function(self)
        if replay then
            -- Apply every recorded change up to the replay's position.
            local at = (GetTime() - replay.started) * replay.speed
            local events = replay.events
            while replay.next <= #events and events[replay.next].t <= at do
                local e = events[replay.next]
                SetCell(e.i, e.id)
                replay.next = replay.next + 1
            end
            if replay.next > #events then
                local done = replay.onDone
                replay = nil
                if done then done() end
            end
            return
        end
        if not self.painting or not active then return end
        if not IsMouseButtonDown("LeftButton") then self.painting = false return end
        local i, row, col = CellAtCursor()
        if i then Brush(row, col) end
    end)

    function canvas:Start(newSize, newPalette)
        replay = nil
        Use(newSize, newPalette)
        Clear()
        self.recording = {}
        startedAt = GetTime()
        self.color = math.min(self.color, #palette)
        active = true
    end

    -- Shows a saved painting (ns.LoadPainting) as it was finished.
    function canvas:ShowPainting(painting)
        replay, active = nil, false
        Use(painting.size, painting.palette)
        Clear()
        for i, id in ipairs(painting.ids) do SetCell(i, id) end
    end

    -- Plays a saved painting back from a blank canvas, speed times as fast; onDone() at the end.
    function canvas:Replay(painting, speed, onDone)
        active = false
        Use(painting.size, painting.palette)
        Clear()
        replay = { events = painting.events, next = 1, started = GetTime(), speed = speed or 1, onDone = onDone }
    end

    function canvas:StopReplay()
        replay = nil
    end

    function canvas:Stop()
        active, self.painting = false, false
    end

    function canvas:IsActive() return active end
    function canvas:IsReplaying() return replay ~= nil end
    return canvas
end

-- Saved paintings --------------------------------------------------------------------------------------------
-- SOLCPuzzleDB.paintings = { newest first, at most MAX_SAVED } of { when, size, seconds, score, traits, owner,
-- number, opponent (duels), palette = "rrggbb..." , ids = one CHARS character per cell (palette index),
-- events = 5 characters per change: time in tenths of a second (2), cell (2), palette index (1) }.

local MAX_SAVED = 40

local function Encode(n, width)
    local s = ""
    for _ = 1, width do
        s = CHARS:sub(n % 64 + 1, n % 64 + 1) .. s
        n = math.floor(n / 64)
    end
    return s
end

local function DecodeNumber(text)
    local n = 0
    for i = 1, #text do n = n * 64 + VALUE[text:sub(i, i)] end
    return n
end

-- Saves the canvas's finished painting. info = { traits, owner, number, seconds, score, opponent }.
-- Returns the number saved, and whether the oldest one had to go.
function ns.SavePainting(canvas, size, palette, info)
    local colors = {}
    for i, c in ipairs(palette) do
        colors[i] = ("%02x%02x%02x"):format(math.floor(c[1] * 255 + 0.5), math.floor(c[2] * 255 + 0.5), math.floor(c[3] * 255 + 0.5))
    end
    local ids = {}
    for i, id in ipairs(canvas.ids) do ids[i] = CHARS:sub(id + 1, id + 1) end
    local events = {}
    for i, e in ipairs(canvas.recording or {}) do
        events[i] = Encode(math.min(4095, math.floor(e.t * 10)), 2) .. Encode(e.i, 2) .. CHARS:sub(e.id + 1, e.id + 1)
    end
    local traits = {}
    for key, id in pairs(info.traits) do traits[key] = id end
    local style = info.style
    SOLCPuzzleDB.paintings = SOLCPuzzleDB.paintings or {}
    local list = SOLCPuzzleDB.paintings
    table.insert(list, 1, { when = time(), size = size, seconds = info.seconds, score = info.score, traits = traits, style = style,
        owner = info.owner, number = info.number, opponent = info.opponent, palette = table.concat(colors),
        ids = table.concat(ids), events = table.concat(events) })
    local dropped = false
    while #list > MAX_SAVED do
        table.remove(list)
        dropped = true
    end
    return #list, dropped
end

-- A saved painting ready for the canvas: { size, palette = { {r,g,b} }, ids = { index }, events = { {t,i,id} } }
-- plus the saved fields.
function ns.LoadPainting(saved)
    local palette = {}
    for hex in saved.palette:gmatch("%x%x%x%x%x%x") do
        palette[#palette + 1] = { tonumber(hex:sub(1, 2), 16) / 255, tonumber(hex:sub(3, 4), 16) / 255,
            tonumber(hex:sub(5, 6), 16) / 255 }
    end
    local ids = {}
    for i = 1, #saved.ids do ids[i] = VALUE[saved.ids:sub(i, i)] end
    local events = {}
    for i = 1, #saved.events, 5 do
        local chunk = saved.events:sub(i, i + 4)
        events[#events + 1] = { t = DecodeNumber(chunk:sub(1, 2)) / 10, i = DecodeNumber(chunk:sub(3, 4)),
            id = VALUE[chunk:sub(5, 5)] }
    end
    local painting = { palette = palette, ids = ids, events = events }
    for key, value in pairs(saved) do
        if painting[key] == nil then painting[key] = value end
    end
    return painting
end
