// Writes ../Rares.lua: every rare and rare elite in WoW Forever, with its zone and level, for the rares list (the
// Kills page's Rares tab) and the rare achievements. Source: references/rares-forever.csv (from Questie's WoW
// Forever database, QuestieDB_Forever.toc; zones a few rares lacked there filled in by hand). Creatures of level 1
// (event and unused ones) are left out.
// Usage: node tools/build-rares.js   No dependencies.

const fs = require("fs");
const path = require("path");

const CSV = path.join(__dirname, "..", "references", "rares-forever.csv");
const OUT = path.join(__dirname, "..", "Rares.lua");

// One CSV line: fields, quoted ones may hold commas.
function fields(line) {
  const out = [];
  let cur = "", quoted = false;
  for (const c of line) {
    if (c === '"') quoted = !quoted;
    else if (c === "," && !quoted) { out.push(cur); cur = ""; }
    else cur += c;
  }
  out.push(cur);
  return out;
}

const rows = fs.readFileSync(CSV, "utf8").trim().split(/\r?\n/).slice(1).map(fields)
  .map(([id, name, level, rank, zone]) => ({ id: +id, name, level: parseInt(level, 10), elite: rank === "Rare Elite", zone }))
  .filter((r) => r.level > 1 && r.zone && r.zone !== "unknown");
const zones = [...new Set(rows.map((r) => r.zone))].sort();
const luaStr = (s) => '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';

const lua = [
  "-- Generated by tools/build-rares.js - don't edit; change references/rares-forever.csv and rerun it.",
  "-- Every rare and rare elite in WoW Forever: ns.Rares[npcID] = { name, zone (index in ns.RareZones), level, elite }.",
  "",
  "local _, ns = ...",
  "",
  "ns.RareZones = {",
  ...zones.map((z) => `    ${luaStr(z)},`),
  "}",
  "",
  "ns.Rares = {",
  ...rows.sort((a, b) => a.id - b.id).map((r) => `    [${r.id}] = { ${luaStr(r.name)}, ${zones.indexOf(r.zone) + 1}, ${r.level}${r.elite ? ", true" : ""} },`),
  "}",
  "",
];
fs.writeFileSync(OUT, lua.join("\n"));
console.log(`Rares.lua: ${rows.length} rares in ${zones.length} zones`);
