// Converts the wooden button art to Media/Button/<state>.blp (normal, hover, pushed, selected) for the button
// skin in UI.lua (ns.UI.SkinButton), and writes ButtonArt.lua with each image's size. The source PNGs live
// outside the addon, in %USERPROFILE%\killtracker-art-extra\Button2\<state>.png (the second version of the art;
// Button\ holds the first, no longer used). A state may be drawn bigger or smaller than normal (hover grows,
// pushed shrinks); the skin draws it at that size relative to normal, centred on the button.
// WoW wants power-of-two textures, so each image is placed in the top-left corner of the next power-of-two
// canvas, unscaled; the skin crops it back with texture coordinates.
// Usage: node tools/convert-buttons.js   No dependencies.

const fs = require("fs");
const os = require("os");
const path = require("path");
const { decodePng, writeBlp } = require("./convert-art");

const SOURCE = path.join(os.homedir(), "killtracker-art-extra", "Button2");
const TARGET = path.join(__dirname, "..", "Media", "Button");
const STATES = ["normal", "hover", "pushed", "selected"];
const nextPow2 = (n) => 2 ** Math.ceil(Math.log2(Math.max(n, 1)));

const lua = ["-- Generated by tools/convert-buttons.js - don't edit. Each button state's art: its size and the size of",
    "-- the texture it sits in (top-left). Textures: Media/Button/<state>.blp. See ns.UI.SkinButton.", "",
    "local _, ns = ...", "", "ns.ButtonArt = {"];
for (const state of STATES) {
    const image = decodePng(path.join(SOURCE, state + ".png"));
    const w = nextPow2(image.width), h = nextPow2(image.height);
    const rgba = Buffer.alloc(w * h * 4);  // transparent padding
    for (let y = 0; y < image.height; y++) {
        image.rgba.copy(rgba, y * w * 4, y * image.width * 4, (y + 1) * image.width * 4);
    }
    writeBlp(path.join(TARGET, state + ".blp"), w, h, rgba);
    lua.push(`    ${state} = { width = ${image.width}, height = ${image.height}, textureWidth = ${w}, textureHeight = ${h} },`);
    console.log(`${state}: ${image.width}x${image.height} in ${w}x${h}`);
}
lua.push("}", "");
fs.writeFileSync(path.join(__dirname, "..", "ButtonArt.lua"), lua.join("\n"));
console.log("Wrote ButtonArt.lua");
