// The wooden header along the top of the main window: where each plank and the two square buttons go. Writes
// HeaderLayout.lua (read by UI.lua) and a preview of the window's top with the real logo and textures
// (%USERPROFILE%\killtracker-art-extra\Wood\header-preview.png), so the layout can be tuned without the game.
// Coordinates: pixels from the window's top-left corner, y downwards (the window is 950 wide). Planks: centre
// (x, y), length w, thickness h, tilt in degrees (clockwise), texture; drawn in this order, later ones on top.
// Usage: node tools/header-layout.js   (after node tools/convert-wood.js and tools/make-role-icons.js)

const fs = require("fs");
const os = require("os");
const path = require("path");
const zlib = require("zlib");
const { readBlp } = require("./convert-art");

const WIDTH = 950;
// Measured from the header design (the logo as the scale: 1.51 game pixels per design pixel). shade darkens a
// plank (1 = as painted): the back row a little, for depth.
const PLANKS = [
  // The back row: left, middle, right.
  { x: 250, y: 10, w: 142, h: 26, tilt: -1.9, texture: "Plank", shade: 0.85 },
  { x: 460, y: 17, w: 252, h: 26, tilt: 0.7, texture: "Plank", shade: 0.85 },
  { x: 710, y: 14, w: 232, h: 26, tilt: 0.4, texture: "Plank", shade: 0.85 },
  // The front row: left (sloping down to the right), middle, right.
  { x: 292, y: 35, w: 226, h: 36, tilt: 2.5, texture: "Plank" },
  { x: 475, y: 31, w: 250, h: 36, tilt: 0, texture: "Plank" },
  { x: 712, y: 34, w: 230, h: 33, tilt: -0.3, texture: "Plank" },
  // A loose piece hanging off the end of the front-left plank.
  { x: 408, y: 56, w: 64, h: 36, tilt: 50, texture: "Piece", shade: 0.95 },
  // A short broken piece standing up between the middle and the right.
  { x: 600, y: 19, w: 54, h: 42, tilt: -12, texture: "Piece" },
];
// The buttons: a square of boards with a painted icon (Media/Icons) on it; x, y = top-left, w x h.
// A "Plank" is drawn in three parts (Media/Wood/PlankLeft, Plank, PlankRight; tools/convert-wood.js): the ends,
// with their nails, keep their shape at PLANK_END times the plank's thickness wide; the middle stretches.
const PLANK_END = 0.645;
// Runes on a button: the sidebar planks' rune (Media/Wood/Rune), one at each side, this share of its height tall.
const RUNE_HEIGHT = 0.6;
const BUTTONS = {
  settings: { x: 818, y: 4, w: 53, h: 50, icon: "Settings", iconSize: 26, runes: true },
  close: { x: 870, y: -4, w: 76, h: 60, icon: "Close", iconSize: 48 },
};

// --- HeaderLayout.lua -----------------------------------------------------------------------------------

const lua = ["-- Generated by tools/header-layout.js - don't edit; change the layout there and rerun it.",
  "-- The wooden header along the top of the main window (UI.lua): planks { x, y (centre, from the window's top-left,",
  "-- y down), w, h, tilt (degrees clockwise), texture, shade (1 = as painted) } in drawing order, and the square buttons { x, y (top-left), w,",
  "-- h, icon, iconSize }.", "", "local _, ns = ...", "", "ns.HeaderLayout = {", "    planks = {"];
for (const p of PLANKS) lua.push(`        { x = ${p.x}, y = ${p.y}, w = ${p.w}, h = ${p.h}, tilt = ${p.tilt}, texture = "${p.texture}", shade = ${p.shade ?? 1} },`);
lua.push("    },", "    buttons = {");
for (const [name, b] of Object.entries(BUTTONS)) {
  lua.push(`        ${name} = { x = ${b.x}, y = ${b.y}, w = ${b.w}, h = ${b.h}, icon = "${b.icon}", iconSize = ${b.iconSize}${b.runes ? ", runes = true" : ""} },`);
}
lua.push("    },", `    plankEnd = ${PLANK_END},`, `    runeHeight = ${RUNE_HEIGHT},`, "}", "");
fs.writeFileSync(path.join(__dirname, "..", "HeaderLayout.lua"), lua.join("\n"));

// --- Preview ---------------------------------------------------------------------------------------------

const MEDIA = path.join(__dirname, "..", "Media");
const LEFT = -30, TOP = -116, W = WIDTH - LEFT + 30, H = 230;
const out = new Float32Array(W * H * 3);
const put = (x, y, rgb, a) => {
  if (x < 0 || y < 0 || x >= W || y >= H || a <= 0) return;
  const i = (y * W + x) * 3;
  for (let k = 0; k < 3; k++) out[i + k] = rgb[k] * a + out[i + k] * (1 - a);
};
// Background, then the window (dark) with the menu column and page area outlines.
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) put(x, y, [32, 32, 34], 1);
for (let y = 0 - TOP; y < H; y++) for (let x = 0 - LEFT; x < WIDTH - LEFT; x++) put(x, y, [18, 18, 20], 1);
for (const [x0, x1] of [[14, 164], [172, WIDTH - 14]]) {
  for (let y = 44 - TOP; y < H; y++) for (let x = x0 - LEFT; x < x1 - LEFT; x++) put(x, y, [10, 10, 12], 1);
}
const sample = (img, u, v) => {
  const x = Math.min(img.width - 1, Math.max(0, u * img.width - 0.5)), y = Math.min(img.height - 1, Math.max(0, v * img.height - 0.5));
  const x0 = Math.floor(x), y0 = Math.floor(y), x1 = Math.min(x0 + 1, img.width - 1), y1 = Math.min(y0 + 1, img.height - 1);
  const fx = x - x0, fy = y - y0, px = (xx, yy, c) => img.rgba[(yy * img.width + xx) * 4 + c];
  return [0, 1, 2, 3].map((c) => (px(x0, y0, c) * (1 - fx) + px(x1, y0, c) * fx) * (1 - fy) + (px(x0, y1, c) * (1 - fx) + px(x1, y1, c) * fx) * fy);
};
// An image drawn into the rectangle centred on (cx, cy), w x h, turned by tilt degrees.
function draw(img, cx, cy, w, h, tilt = 0, shade = 1, tint = [1, 1, 1]) {
  const a = (tilt * Math.PI) / 180, cos = Math.cos(a), sin = Math.sin(a);
  const reach = Math.ceil(Math.hypot(w, h) / 2) + 1;
  for (let y = Math.floor(cy - reach); y <= cy + reach; y++) {
    for (let x = Math.floor(cx - reach); x <= cx + reach; x++) {
      const dx = x + 0.5 - cx, dy = y + 0.5 - cy;
      const lx = dx * cos + dy * sin, ly = -dx * sin + dy * cos;  // into the unturned rectangle
      const u = lx / w + 0.5, v = ly / h + 0.5;
      if (u < 0 || u > 1 || v < 0 || v > 1) continue;
      const [r, g, b, alpha] = sample(img, u, v);
      put(x - LEFT, y - TOP, [r * shade * tint[0], g * shade * tint[1], b * shade * tint[2]], alpha / 255);
    }
  }
}
const textures = {};
const texture = (file) => (textures[file] ??= readBlp(path.join(MEDIA, file + ".blp")));
// A plank in its three parts, along its tilted line (as UI.lua draws it).
function drawPlank(p) {
  const shade = p.shade ?? 1;
  if (p.texture !== "Plank") return draw(texture("Wood/" + p.texture), p.x, p.y, p.w, p.h, p.tilt, shade);
  const end = Math.min(p.h * PLANK_END, p.w / 2 - 1), a = (p.tilt * Math.PI) / 180;
  const along = (d) => [p.x + Math.cos(a) * d, p.y + Math.sin(a) * d];
  draw(texture("Wood/Plank"), p.x, p.y, p.w - 2 * end + 2, p.h, p.tilt, shade);
  draw(texture("Wood/PlankLeft"), ...along(-(p.w - end) / 2), end, p.h, p.tilt, shade);
  draw(texture("Wood/PlankRight"), ...along((p.w - end) / 2), end, p.h, p.tilt, shade);
}
for (const p of PLANKS) drawPlank(p);
for (const b of Object.values(BUTTONS)) {
  draw(texture("Wood/Square"), b.x + b.w / 2, b.y + b.h / 2, b.w, b.h);
  draw(texture("Icons/" + b.icon), b.x + b.w / 2, b.y + b.h / 2, b.iconSize, b.iconSize);
  if (b.runes) {
    const rh = b.h * RUNE_HEIGHT, rw = rh / 2;
    for (const x of [b.x + 3 + rw / 2, b.x + b.w - 3 - rw / 2]) draw(texture("Wood/Rune"), x, b.y + b.h / 2, rw, rh, 0, 1, [0.22, 0.36, 0.78]);
  }
}
// The logo on top, where UI.lua puts it: 210 square, its top-left 21 left of and 110 above the window's.
draw(texture("Logo"), -21 + 105, -110 + 105, 210, 210);

const raw = Buffer.alloc((W * 3 + 1) * H);
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) for (let k = 0; k < 3; k++) {
  raw[y * (W * 3 + 1) + 1 + x * 3 + k] = Math.round(Math.min(255, out[(y * W + x) * 3 + k]));
}
const crcTable = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
const crc = (b) => { let c = 0xffffffff; for (const v of b) c = crcTable[(c ^ v) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
const chunk = (type, data) => { const l = Buffer.alloc(4); l.writeUInt32BE(data.length); const td = Buffer.concat([Buffer.from(type), data]); const c = Buffer.alloc(4); c.writeUInt32BE(crc(td)); return Buffer.concat([l, td, c]); };
const header = Buffer.alloc(13); header.writeUInt32BE(W, 0); header.writeUInt32BE(H, 4); header[8] = 8; header[9] = 2;
const preview = path.join(os.homedir(), "killtracker-art-extra", "Wood", "header-preview.png");
fs.writeFileSync(preview, Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", header),
  chunk("IDAT", zlib.deflateSync(raw)), chunk("IEND", Buffer.alloc(0))]));
console.log(`Wrote HeaderLayout.lua and ${preview}`);
