// The wooden window frame (on every page) and the new Overview (the book of boards with the character card):
// where each part goes. Writes OverviewLayout.lua (read by UI.lua and OverviewCard.lua) and a preview
// (%USERPROFILE%\killtracker-art-extra\Overview\preview.png): the design on the left, this layout drawn with
// the real textures on the right, so the two can be compared without the game.
// Both the frame and the Overview's inside are the designer's own exports (tools/frame-art.js says where they sit
// in the window). The card's live parts (the name, the photo with the model, the icons, the signature) go on the
// spots measured here in the inside export (export pixels), converted to window pixels.
// Window coordinates: pixels from the window's top-left corner, y down (the window is 950 x 625). A piece: centre
// (x, y), w x h before turning, tilt in degrees (clockwise), texture (Media/Overview), shade, coords (texture
// crop: left, right, top, bottom); drawn in this order, later ones on top.
// Usage: node tools/overview-layout.js   (after node tools/convert-overview.js)

const fs = require("fs");
const os = require("os");
const path = require("path");
const zlib = require("zlib");
const { decodePng, readBlp } = require("./convert-art");
const { FRAME_PARTS, INSIDE_ART, INSIDE_CAPS, capArea } = require("./frame-art");

const ART = path.join(os.homedir(), "killtracker-art-extra", "Overview");
const DESIGN = path.join(ART, "design.png");  // the designer's mockup (a screenshot of the window, its top 90 down)
const DESIGN_TOP = 90;
const INSIDE_SIZE = { w: 813, h: 734 };       // INSIDE.png, in the top-left of its 1024x1024 texture

// Export pixels of the inside to window pixels.
const wx = (x) => INSIDE_ART.left + x * INSIDE_ART.scale;
const wy = (y) => INSIDE_ART.top + y * INSIDE_ART.scale;
const rect = (x0, y0, x1, y1) => ({ x: (wx(x0) + wx(x1)) / 2, y: (wy(y0) + wy(y1)) / 2, w: (x1 - x0) * INSIDE_ART.scale, h: (y1 - y0) * INSIDE_ART.scale });
const spot = (x, y, size) => ({ x: wx(x), y: wy(y), size: size * INSIDE_ART.scale });

// The frame, on every page, each part where it sits in the export. Everything between the posts, above the
// bottom, is the page area (INNER).
const FRAME = FRAME_PARTS.map((p) => ({ x: (p.x0 + p.x1) / 2, y: (p.y0 + p.y1) / 2, w: p.x1 - p.x0, h: p.y1 - p.y0, tilt: 0, texture: p.texture }));
const INNER = { left: 206, right: 923, top: 44, bottom: 588 };

// The Overview's inside: the whole export, under the frame.
const PAGE = [{ ...rect(0, 0, INSIDE_SIZE.w, INSIDE_SIZE.h), tilt: 0, texture: "Inside",
  coords: [0, INSIDE_SIZE.w / 1024, 0, INSIDE_SIZE.h / 1024] }];
// The grey squares on the spine's ends, cut out of the export (tools/convert-overview.js) and drawn exactly where
// they were, over the frame's bottom and the header.
const SPINE_CAPS = INSIDE_CAPS.map((cap) => {
  const { x0, y0, x1, y1 } = capArea(cap);
  return { ...rect(x0, y0, x1, y1), tilt: 0, texture: cap.texture, coords: [0, (x1 - x0) / 128, 0, (y1 - y0) / 128] };
});

// The card's live parts, on the export's sample character's spots.
const CARD = {
  label: rect(527.3, 117.3, 713.3, 152.7),              // the name, in the middle of the grey label
  arrows: [rect(473.3, 114, 527.3, 159.3), rect(713.3, 113.3, 768.3, 158.3)],  // the end planks: previous, next
  arrowGlyphs: [rect(485, 121.7, 510, 151.7), rect(728.3, 118, 758.3, 153)],  // the white arrows on them (lit on hover)
  photo: rect(491.7, 192.7, 754, 496.7),                 // inside the photo's black border
  icons: {
    race: spot(522.7, 226.7, 47),
    gender: spot(522.5, 277, 46),
    class: spot(715.8, 230.3, 52),
    professions: [spot(717.3, 410, 52), spot(717.3, 466.7, 52)],
    secondary: [spot(512.5, 421.2, 42), spot(538.3, 447.5, 42), spot(514.2, 472.5, 42)],
  },
  signature: rect(513, 511.7, 733, 566.7),
};

// --- OverviewLayout.lua ----------------------------------------------------------------------------------

const num = (v) => String(Math.round(v * 1000) / 1000);
const piece = (p) => `{ x = ${num(p.x)}, y = ${num(p.y)}, w = ${num(p.w)}, h = ${num(p.h)}, tilt = ${num(p.tilt)}, texture = "${p.texture}"`
  + `${p.shade ? `, shade = ${num(p.shade)}` : ""}${p.coords ? `, coords = { ${p.coords.map(num).join(", ")} }` : ""} }`;
const area = (r) => `{ x = ${num(r.x)}, y = ${num(r.y)}, w = ${num(r.w)}, h = ${num(r.h)} }`;
const at = (s) => `{ x = ${num(s.x)}, y = ${num(s.y)}, size = ${num(s.size)} }`;
const lua = [
  "-- Generated by tools/overview-layout.js - don't edit; change the layout there and rerun it.",
  "-- The wooden window frame (UI.lua) and the new Overview's inside and character card (OverviewCard.lua), in window",
  "-- pixels (from its top-left, y down). Pieces: { x, y (centre), w, h, tilt (degrees clockwise), texture",
  "-- (Media/Overview), shade, coords (texture crop) } in drawing order; areas: { x, y (centre), w, h }; spots:",
  "-- { x, y (centre), size }.",
  "",
  "local _, ns = ...",
  "",
  "ns.OverviewLayout = {",
  "    frame = {", ...FRAME.map((p) => `        ${piece(p)},`), "    },",
  `    inner = { left = ${INNER.left}, right = ${INNER.right}, top = ${INNER.top}, bottom = ${INNER.bottom} },`,
  "    page = {", ...PAGE.map((p) => `        ${piece(p)},`), "    },",
  "    spineCaps = {", ...SPINE_CAPS.map((p) => `        ${piece(p)},`), "    },",
  "    card = {",
  `        label = ${area(CARD.label)},`,
  `        arrows = { ${CARD.arrows.map(area).join(", ")} },`,
  `        arrowGlyphs = { ${CARD.arrowGlyphs.map(area).join(", ")} },`,
  `        photo = ${area(CARD.photo)},`,
  "        icons = {",
  `            race = ${at(CARD.icons.race)},`,
  `            gender = ${at(CARD.icons.gender)},`,
  `            class = ${at(CARD.icons.class)},`,
  `            professions = { ${CARD.icons.professions.map(at).join(", ")} },`,
  `            secondary = { ${CARD.icons.secondary.map(at).join(", ")} },`,
  "        },",
  `        signature = ${area(CARD.signature)},`,
  "    },",
  "}",
  "",
];
fs.writeFileSync(path.join(__dirname, "..", "OverviewLayout.lua"), lua.join("\n"));

// --- Preview ---------------------------------------------------------------------------------------------

if (!fs.existsSync(DESIGN)) {
  console.log("OverviewLayout.lua written (no design.png for the preview)");
  process.exit(0);
}
const design = decodePng(DESIGN);
const W = design.width, H = design.height;
const out = new Float32Array(W * H * 3);
for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {  // the design's backdrop (the game world) dimmed
  const i = (y * W + x) * 4;
  for (let c = 0; c < 3; c++) out[(y * W + x) * 3 + c] = design.rgba[i + c] * 0.35;
}
const put = (x, y, rgb, a) => {
  if (x < 0 || y < 0 || x >= W || y >= H || a <= 0) return;
  const i = (y * W + x) * 3;
  for (let k = 0; k < 3; k++) out[i + k] = rgb[k] * a + out[i + k] * (1 - a);
};
const sample = (img, u, v) => {
  const x = Math.min(img.width - 1, Math.max(0, u * img.width - 0.5)), y = Math.min(img.height - 1, Math.max(0, v * img.height - 0.5));
  const x0 = Math.floor(x), y0 = Math.floor(y), x1 = Math.min(x0 + 1, img.width - 1), y1 = Math.min(y0 + 1, img.height - 1);
  const fx = x - x0, fy = y - y0, px = (xx, yy, c) => img.rgba[(yy * img.width + xx) * 4 + c];
  return [0, 1, 2, 3].map((c) => (px(x0, y0, c) * (1 - fx) + px(x1, y0, c) * fx) * (1 - fy) + (px(x0, y1, c) * (1 - fx) + px(x1, y1, c) * fx) * fy);
};
const textures = {};
const texture = (name) => (textures[name] ??= readBlp(path.join(__dirname, "..", "Media", "Overview", name + ".blp")));
// A piece in window coordinates, drawn where it lands in the design.
function draw(p, img = texture(p.texture)) {
  const a = (p.tilt * Math.PI) / 180, cos = Math.cos(a), sin = Math.sin(a), shade = p.shade ?? 1;
  const [l, r, t, b] = p.coords || [0, 1, 0, 1];
  const cx = p.x, cy = p.y + DESIGN_TOP, reach = Math.hypot(p.w, p.h) / 2 + 2;
  for (let y = Math.floor(cy - reach); y <= cy + reach; y++) {
    for (let x = Math.floor(cx - reach); x <= cx + reach; x++) {
      const dx = x + 0.5 - cx, dy = y + 0.5 - cy;
      const lx = dx * cos + dy * sin, ly = -dx * sin + dy * cos;  // into the piece's own frame
      const u = lx / p.w + 0.5, v = ly / p.h + 0.5;
      if (u < 0 || u > 1 || v < 0 || v > 1) continue;
      const [red, green, blue, alpha] = sample(img, l + u * (r - l), t + v * (b - t));
      put(x, y, [red * shade, green * shade, blue * shade], alpha / 255);
    }
  }
}
for (const p of PAGE) draw(p);
for (const p of FRAME) draw(p);
for (const p of SPINE_CAPS) draw(p);
// The live parts: the photo as a sky-to-grass gradient, the icons, lines where the name and signature go.
{
  const r = CARD.photo;
  for (let y = Math.round(r.y - r.h / 2); y < r.y + r.h / 2; y++) {
    const t = (y - (r.y - r.h / 2)) / r.h;
    for (let x = Math.round(r.x - r.w / 2); x < r.x + r.w / 2; x++) put(x, y + DESIGN_TOP, [240 - 120 * t, 200 - 40 * t, 190 - 110 * t], 1);
  }
}
const icon = (name, s) => draw({ x: s.x, y: s.y, w: s.size, h: s.size, tilt: 0 }, texture("Icons/" + name));
icon("Race_SKYBORNE", CARD.icons.race);
icon("Gender_MALE", CARD.icons.gender);
icon("Class_DRUID", CARD.icons.class);
icon("Prof_LEATHERWORKING", CARD.icons.professions[0]);
icon("Prof_SKINNING", CARD.icons.professions[1]);
icon("Prof_COOKING", CARD.icons.secondary[0]);
icon("Prof_FISHING", CARD.icons.secondary[1]);
icon("Prof_FIRSTAID", CARD.icons.secondary[2]);
for (const r of [CARD.label, CARD.signature]) {
  for (let x = Math.round(r.x - r.w / 2); x < r.x + r.w / 2; x++) {
    put(x, Math.round(r.y - r.h / 2 + DESIGN_TOP), [0, 255, 255], 1);
    put(x, Math.round(r.y + r.h / 2 + DESIGN_TOP), [0, 255, 255], 1);
  }
}

// Side by side: the design's window part, then the preview's.
const X0 = 160, X1 = W, Y0 = 60, CW = X1 - X0, CH = H - Y0, PW = CW * 2 + 10;
const raw = Buffer.alloc((PW * 3 + 1) * CH);
for (let y = 0; y < CH; y++) {
  for (let x = 0; x < CW; x++) {
    const d = ((y + Y0) * W + x + X0) * 4, p = ((y + Y0) * W + x + X0) * 3;
    const o = y * (PW * 3 + 1) + 1;
    raw.set([design.rgba[d], design.rgba[d + 1], design.rgba[d + 2]], o + x * 3);
    raw.set([out[p], out[p + 1], out[p + 2]].map((v) => Math.max(0, Math.min(255, Math.round(v)))), o + (CW + 10 + x) * 3);
  }
}
const table = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
const crc = (buf) => { let c = 0xffffffff; for (const b of buf) c = table[(c ^ b) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
const chunk = (type, data) => {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type), data]);
  const sum = Buffer.alloc(4); sum.writeUInt32BE(crc(body));
  return Buffer.concat([len, body, sum]);
};
const header = Buffer.alloc(13); header.writeUInt32BE(PW, 0); header.writeUInt32BE(CH, 4); header[8] = 8; header[9] = 2;
fs.writeFileSync(path.join(ART, "preview.png"), Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", header),
  chunk("IDAT", zlib.deflateSync(raw)), chunk("IEND", Buffer.alloc(0))]));
console.log("OverviewLayout.lua and preview.png written");
